# Fabric Properties
# check these on https://www.fabricmc.net/develop/
minecraft_version = 26.3-snapshot-4
mcVersion = 260300

# Fabric Mod Metadata
carpet_dependency = >=26.2
minecraft_dependency = >=26.3-alpha.4

# Build Infomation
game_versions = 26.3-snapshot-4

# Mod Dependency
# check available versions on maven for the given minecraft version you are using
# https://masa.dy.fi/maven/carpet/fabric-carpet/
carpet_core_version = 26.3-beta-2+v260709

# check these on https://fabricmc.net/develop
# fabric_api_version = 0.140.1+26.1
