# Fabric Properties
# check these on https://www.fabricmc.net/develop/
minecraft_version = 26.3

# Fabric Mod Metadata
carpet_dependency = >=26.3
minecraft_dependency = >=26.3

# Build Infomation
game_versions = 26.3

# Mod Dependency
# check available versions on maven for the given minecraft version you are using
# https://modrinth.com/mod/carpet/versions
carpet_core_version = 26.3

# check these on https://fabricmc.net/develop
# fabric_api_version = 0.140.1+26.1
