name: step.build

on:
  workflow_call:
    inputs:
      release:
        type: boolean
        required: false
        default: false
      mixin_audit:
        type: boolean
        required: false
        default: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3.6.0
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Cache gradle files
        uses: actions/cache@v3.0.11
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ./.gradle/loom-cache
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle', '**/gradle.properties', '**/*.accesswidener') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew classes --parallel
          ./gradlew build
        env:
          BUILD_ID: ${{ github.run_number }}
          BUILD_RELEASE: ${{ inputs.release }}

      - name: Run Mixin Audit Check
        if: ${{ inputs.mixin_audit }}
        timeout-minutes: 10
        run: |
          mkdir -p ./run
          echo eula=true > ./run/eula.txt
          ./gradlew runMixinAudit

      - uses: actions/upload-artifact@v3.1.1
        with:
          name: build-artifacts
          path: versions/*/build/libs/
