name: Dev Builds

on:
  push:
    paths:
      - "*.gradle"
      - "gradle.properties"
      - "src/**"
      - "versions/**"
      - ".github/**"
  pull_request:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      mixin_audit: true
      ci_release: ${{ github.event_name == 'push' && github.ref_name != 'master' }}
    secrets:
      GITEE_API_TOKEN: ${{ secrets.GITEE_API_TOKEN }}